### ISSUE TITLE
WinAuth is not portable

### ISSUE THREAD

**Issue by Super99Master** [pavletabata/winauth#4]
I don't know if this is an issue or intended but the original is "WinAuth is a portable, open-source Authenticator".
This version is not portable or atleast not autocontained.
You can have multiple exe and all of them will have a shared database/state. 
You can delete the .exe, redownload it from github at it will get the old state instead of a new empty state.

**Comment by ccinv** [comment]
For me it is portable. I can repalce old winauth with this fork and state is still there.

**Comment by ttodua** [comment]
I've updated the readme, where you can see how to make it portable the way you say. You need to place `winAuth.xml` aside to your exe.
