### ISSUE TITLE
Wrong order

### ISSUE THREAD

**Issue by Dominiquini** [pavletabata/winauth#5]
The last version (3.6.6.1) not show the items on the correct order. Every time that I reorder my entries and exit the app, when I reopen the app, the order is wrong!

The last version of the original app (3.5.1) works correctly!

Thanks.

**Comment by ttodua** [comment]
I will try to add that option later in the following week.

**Comment by Dominiquini** [comment]
The version 3.6.6.2 still have this wrong order bug, and now very time I start the application, an error popup appear warning me the the applications was updated and a backup was made...

Thanks

**Comment by ttodua** [comment]
@Dominiquini I'll check this in few mins.

**Comment by ttodua** [comment]
can you please mention the exact error message you get?

**Comment by ttodua** [comment]
Update . 
Can you try this and let me know:
https://github.com/ttodua/winauth/releases/tag/3.6.6.3.b

1) there is additional checkbox added in settings, named "sort alphabetically" and uncheck it and see if after restart the items are still auto-sorted
2) if still "backup made" or whatever message appears, please post an exact message of the error.

**Comment by ttodua** [comment]
update at: https://github.com/ttodua/winauth/releases/tag/3.6.6.3.b

**Comment by ttodua** [comment]
Please confirm that issue fixed on your side, so i'll move that into releases.

**Comment by Dominiquini** [comment]
It's working now! All my issues are resolved!

Thanks.
