### ISSUE TITLE
If using the latest 3.6.6.1 without a pre-existing WinAuth use, an error on startup is presented since WinAuth.xml is missing

### ISSUE THREAD

**Issue by mjpcomp** [pavletabata/winauth#6]
When you run the latest release, 3.6.6.1, without having previously run WinAuth (so no WinAuth.xml or anything), the portable version fails to run with the following error:
![image](https://user-images.githubusercontent.com/7637082/174320748-329fc8c2-524b-41f1-a62c-7a79c6fe296a.png)

Need to add some code detection that if there is no WinAuth.xml file in the %AppData%/WinAuth folder, or, an existing WinAuth.xml, bring up the blank WinAuth screen... Have to use an older version first (or create a blank/use an existing WinAuth.xml file) to get this version working.

**Comment by ttodua** [comment]
Thanks for report! 
I'll take a look into that whenever time permits.

**Comment by mjpcomp** [comment]
In WinAuthHelper.cs, was all of this code supposed to be removed?

![image](https://user-images.githubusercontent.com/7637082/174335663-9ef22f9f-177b-47a1-8763-b59bf454ddee.png)

**Comment by ttodua** [comment]
If you have a chance to make a PR, it will be welcomed

**Comment by ttodua** [comment]
i've seen that commit, but if you look a bit several lines upper, the code is moved there.

**Comment by ttodua** [comment]
fixed the bug and submitted an updated version 3.6.6.2. thanks for report again.
